act/meetings/urls.py
from django.urls import path

from act.meetings.views import (
    meeting_list_view,
    organization_detail_view,
    organization_list_view,
    representative_detail_view,
    representative_list_view,
)

app_name = "meetings"
urlpatterns = [
    path("representatives/", view=representative_list_view, name="representative_list"),
    path(
        "representatives/<int:pk>/",
        view=representative_detail_view,
        name="representative_detail",
    ),
    path("organizations/", view=organization_list_view, name="organization_list"),
    path(
        "organizations/<int:pk>/",
        view=organization_detail_view,
        name="organization_detail",
    ),
    path("meetings/", view=meeting_list_view, name="meeting_list"),
]

act/users/urls.py
from django.urls import path

from act.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from act.meetings.views import home_view

urlpatterns = i18n_patterns(
    path("", view=home_view, name="home"),
    path("meetings/", include("act.meetings.urls", namespace="meetings")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

act/pages/models.py
from django.contrib.flatpages.models import FlatPage
from django.db import models
from django.utils.translation import ugettext_lazy as _

FlatPage.add_to_class(
    "meta_description", models.TextField(_("Metadata description for SEO"), blank=True)
)

act/presentations/models.py
from ckeditor.fields import RichTextField
from django.db.models.fields import CharField
from django.utils.translation import ugettext_lazy as _

from act.utils.models import SingletonModel


class Presentations(SingletonModel):
    """Specfic presentation texts for the home page, the representatives, organizations and meetings pages"""

    class Meta:
        verbose_name = _("Presentation texts")
        verbose_name_plural = _("Presentation texts")

    home_title = CharField(
        _("Title in Home page"),
        blank=True,
        max_length=255,
        default=_("Anti Corruption Toolkit"),
    )
    home_text = RichTextField(
        _("Text in Home page"),
        blank=True,
    )
    representatives_text = RichTextField(
        _("Text in Representatives page"),
        blank=True,
    )
    meetings_text = RichTextField(
        _("Text in Meetings page"),
        blank=True,
    )
    organizations_text = RichTextField(
        _("Text in Organizations page"),
        blank=True,
    )

    def __str__(self):
        return "{}".format(_("Presentations texts"))

act/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for ACT."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

act/utils/models.py
from django.db import models


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

act/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

act/meetings/views.py
from datetime import date, datetime
from typing import Any, Dict

from django.conf import settings
from django.db.models.aggregates import Avg, Count
from django.db.models.expressions import F
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from act.meetings.models import Issue, Meeting, Organization, Representative
from act.presentations.models import Presentations


class HomeView(TemplateView):

    slug_field = "home"
    slug_url_kwarg = "home"
    template_name = "pages/home.html"

    @staticmethod
    def annotate_top_representatives_by_interests(n_top=10):
        """It's a complex extraction that cannot be performed by the ORM

        :param n_top:
        :return: a list of Representative objects, annotated with 'n' field
        """
        tuples = sorted(
            [
                (
                    r,
                    len(
                        set(r.shares.values_list("company_name", flat=True))
                        | set(r.posts.values_list("company_name", flat=True))
                    ),
                )
                for r in Representative.objects.all()
            ],
            key=lambda x: x[1],
            reverse=True,
        )[:n_top]
        objects = []
        for t in tuples:
            o = t[0]
            o.n = t[1]
            objects.append(o)
        return objects

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        n_top = settings.N_TOP
        context.update(
            {
                "presentation_texts": Presentations.objects.first(),
                "meetings": {
                    "first_date": Meeting.objects.order_by("date").first().date,
                    "n_up_to_now": Meeting.objects.filter(
                        date__lt=datetime.now()
                    ).count(),
                    "n_from_now_on": Meeting.objects.filter(
                        date__gte=datetime.now()
                    ).count(),
                    "top_reprs": Representative.objects.annotate(
                        n=Count("meetings")
                    ).order_by("-n")[:n_top],
                    "top_reprs_all_url": reverse("meetings:representative_list") + "",
                    "top_orgs": Organization.objects.annotate(
                        n=Count("lobbyings__meetings")
                    ).order_by("-n")[:n_top],
                    "top_orgs_all_url": reverse("meetings:organization_list") + "",
                    "timeline_monthly": Meeting.objects.values(
                        "date__year", "date__month"
                    )
                    .annotate(n=Count(("date__year", "date__month")))
                    .values("date__year", "date__month", "n")
                    .order_by("date__year", "date__month"),
                    "timeline_weekly": Meeting.objects.values(
                        "date__year", "date__month", "date__week"
                    )
                    .annotate(n=Count(("date__year", "date__month", "date__week")))
                    .values("date__year", "date__month", "date__week", "n")
                    .order_by("date__year", "date__month", "date__week"),
                    "issues_cloud": Issue.objects.annotate(n=Count("meetings")).values(
                        "name", "n"
                    ),
                    "last_n": Meeting.objects.filter(date__lt=date.today()).order_by(
                        "-date"
                    )[:n_top],
                    "next_n": Meeting.objects.filter(date__gte=date.today()).order_by(
                        "date"
                    )[:n_top],
                    "last_n_all_url": reverse("meetings:meeting_list")
                    + "#"
                    + '{"col_1"%3A{"flt"%3A"<%3D'
                    + datetime.now().strftime("%Y-%m-%d")
                    + '"%2C"sort"%3A{"descending"%3Atrue}}}',
                    "next_n_all_url": reverse("meetings:meeting_list")
                    + "#"
                    + '{"col_1"%3A{"flt"%3A">'
                    + datetime.now().strftime("%Y-%m-%d")
                    + '"%2C"sort"%3A{"descending"%3Afalse}}}',
                },
                "interests": {
                    "n_representatives": Representative.objects.count(),
                    "avg_income": Representative.objects.aggregate(
                        av=Avg("last_income")
                    )["av"],
                    "n_organizations_of_interest": len(
                        set(
                            Representative.objects.filter(
                                shares__isnull=False
                            ).values_list("shares__company_name", flat=True)
                        )
                        | set(
                            Representative.objects.filter(
                                posts__isnull=False
                            ).values_list("posts__company_name", flat=True)
                        )
                    ),
                    "top_reprs_by_income": Representative.objects.annotate(
                        n=F("last_income")
                    ).order_by("-last_income")[:n_top],
                    "top_reprs_by_income_all_url": reverse(
                        "meetings:representative_list"
                    )
                    + "",
                    "top_reprs_by_interests": self.annotate_top_representatives_by_interests(
                        n_top
                    ),
                    "top_reprs_by_interests_all_url": reverse(
                        "meetings:representative_list"
                    )
                    + "",
                },
            }
        )
        return context


class RepresentativeListView(ListView):
    model = Representative
    paginate_by = 100

    def get_queryset(self):
        """Annotate all representatives with the n. of meetings and interests"""

        qs = super().get_queryset()
        qs = qs.annotate(n_meetings=Count("meetings"))
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "presentation_text": Presentations.objects.first(),
            }
        )
        return context


class RepresentativeDetailView(DetailView):
    model = Representative

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        context.update(
            {
                "timeline_monthly": obj.meetings.values("date__year", "date__month")
                .annotate(n=Count(("date__year", "date__month")))
                .values("date__year", "date__month", "n")
                .order_by("date__year", "date__month"),
                "issues_cloud": obj.meetings.filter(issues__isnull=False)
                .values("issues__name")
                .annotate(n=Count("issues__name"))
                .annotate(name=F("issues__name"))
                .values("name", "n"),
            }
        )
        return context


class OrganizationListView(ListView):
    model = Organization
    paginate_by = 100

    def get_queryset(self):
        """Annotate all representatives with the n. of meetings and interests"""

        qs = super().get_queryset()
        qs = qs.annotate(n_meetings=Count("lobbyings__meetings"))
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "presentation_text": Presentations.objects.first(),
                "org_types_data": [
                    {
                        "org_type": getattr(
                            Organization.OrgTypes, f"ORG_{ot[0]}"
                        ).label,
                        "n_organizations": ot[1],
                    }
                    for ot in Organization.objects.values_list("org_type").annotate(
                        n=Count("org_type")
                    )
                ],
            }
        )
        return context


class OrganizationDetailView(DetailView):
    model = Organization

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        context.update(
            {
                "timeline_monthly": obj.meetings.values("date__year", "date__month")
                .annotate(n=Count(("date__year", "date__month")))
                .values("date__year", "date__month", "n")
                .order_by("date__year", "date__month"),
                "issues_cloud": obj.meetings.filter(issues__isnull=False)
                .values("issues__name")
                .annotate(n=Count("issues__name"))
                .annotate(name=F("issues__name"))
                .values("name", "n"),
            }
        )
        return context


class MeetingListView(ListView):
    model = Meeting
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "presentation_text": Presentations.objects.first(),
            }
        )

        return context


home_view = HomeView.as_view()
representative_list_view = RepresentativeListView.as_view()
representative_detail_view = RepresentativeDetailView.as_view()
organization_list_view = OrganizationListView.as_view()
organization_detail_view = OrganizationDetailView.as_view()
meeting_list_view = MeetingListView.as_view()

act/pages/views.py
# Create your views here.

act/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

act/templates/meetings/meeting_list.html
{% extends "base.html" %}
{% load i18n static %}

{% block header %}
  {% include "meetings/includes/page_list_header.html" with page_type="meetings_list" text=presentation_text.meetings_text %}
{% endblock header %}

{% block content %}
    <section id="items-container" class="container-lg px-lg-4">
        <div>
            <button class="btn btn-light" value="" onclick="filter(event);">All</button>
            <button class="btn btn-light" value="-6" onclick="filter(event);">{% trans "-6m" %}</button>
            <button class="btn btn-light" value="-5" onclick="filter(event);">{% trans "-5m" %}</button>
            <button class="btn btn-light" value="-4" onclick="filter(event);">{% trans "-4m" %}</button>
            <button class="btn btn-light" value="-3" onclick="filter(event);">{% trans "-3m" %}</button>
            <button class="btn btn-light" value="-2" onclick="filter(event);">{% trans "-2m" %}</button>
            <button class="btn btn-light" value="-1" onclick="filter(event);">{% trans "-1m" %}</button>
            <button class="btn btn-light" value="0" onclick="filter(event);">{% trans "Now" %}</button>
            <button class="btn btn-light" value="+1" onclick="filter(event);">{% trans "+1m" %}</button>
            <button class="btn btn-light" value="+2" onclick="filter(event);">{% trans "+2m" %}</button>
            <button class="btn btn-light" value="+3" onclick="filter(event);">{% trans "+3m" %}</button>
            <button class="btn btn-light" value="+4" onclick="filter(event);">{% trans "+4m" %}</button>
            <button class="btn btn-light" value="+5" onclick="filter(event);">{% trans "+5m" %}</button>
            <button class="btn btn-light" value="+6" onclick="filter(event);">{% trans "+6m" %}</button>
        </div>
        <div class="table-responsive-lg">
            <table id="items-data-table" class="table table-striped mt-4 table-responsive-lg">
                <thead>
                    <tr>
                        <th scope="col">{% trans "Subject" %}</th>
                        <th scope="col">{% trans "Date" %}</th>
                        <th scope="col">{% trans "Representatives" %}</th>
                        <th scope="col">{% trans "Person/Orgs" %}</th>
                        <th scope="col">{% trans "Issues" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <td>{{ item.subject }}</td>
                        <td>{{ item.date }}</td>
                        <td>
                            {% for r in item.representatives.all %}
                                <a href="{% url 'meetings:representative_detail' r.pk %}">{{ r.name }}</a>{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% for l in item.lobbyists.all %}
                                {{ l.person.name }}
                                {% if l.organization %}
                                    {% trans "for" %}
                                    <a href="{% url 'meetings:organization_detail' l.organization.pk %}">{{ l.organization.name }}</a>
                                {% endif %}{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% for i in item.issues.all %}
                                <a href='#{"col_4"%3A{"flt"%3A"{{ i.name }}"}}'>{{ i.name }}</a>{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>
{% endblock %}

{% block css %}
    {{ block.super }}
    <style>
        caption {
          caption-side: top;
        }
    </style>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static "js/moment-with-locales.js" %}"></script>
    <script src="{% static "js/tablefilter/tablefilter.js" %}"></script>
    <script>
    // filter by months
    function filter(evt){
        var elm = evt.target;
        var dateFmt = 'YYYY-MM-DD';

        var query = '';
        var liminf, limsup;


        if (elm.value.length > 0 ) {
            v = parseInt(elm.value)
            if (v === 0) {
                liminf = moment().subtract(15, 'days');
                limsup = moment().add(15, 'days');
            } else if (v < 0) {
                liminf = moment().add(v, 'months');
                limsup = moment().add(v+1, 'months');
            } else {
                liminf = moment().add(v-1, 'months');
                limsup = moment().add(v, 'months');
            }
            query += tf.geOperator + liminf.format(dateFmt) + tf.anOperator + tf.leOperator + limsup.format(dateFmt);
        }

        // set the column's filter value
        tf.setFilterValue(1, query);

        // filter the table
        tf.filter();

        // clear previously marked element
        if(tf.selectedInterval) {
            tf.selectedInterval.classList.remove('btn-primary');
            tf.selectedInterval.classList.remove('btn-light');
        }

        // mark selected letter
        elm.classList.remove('btn-light');
        elm.classList.add('btn-primary');

        // keep reference of selected element
        tf.selectedInterval = elm;
    }

    var tf = new TableFilter('items-data-table', {
        base_path: "{% static "js/tablefilter/" %}",
        state: {
          types: ['hash'],
          filters: true,
          sort: true,
        },
        rows_counter: {
            text: "{% trans "n. results: " %}"
        },
        auto_filter: {
            delay: 400 //milliseconds
        },
        status_bar: false,
        btn_reset: true,
        help_instructions: {
            'text': '{% trans "Use the filters above each column to filter and limit table data."%} ' +
                '{% trans "Advanced searches can be performed by using the following operators: &lt;, &lt;=, &gt;, &gt;=, =, *, !, {, }, ||,&amp;&amp;, [empty], [nonempty], rgx:"%}'
        },
        col_types: [
            'string',
            { type: 'date', locale: 'it' },
            'string',
            'string',
            'string',
        ],
        no_results_message: {
            content: "{% trans "No results" %}"
        },
        ignore_diacritics: true,
        {#single_filter: {#}
        {#    exclude_cols: [1],#}
        {#    css_class: 'form-control',#}
        extensions: [{ name: 'sort' }],
        // allows Bootstrap table styling
        themes: [{
            name: 'transparent'
        }],
       // hide date filter
       on_filters_loaded: function(tf) {
            tf.dom().rows[0].children[1].children[0].style.display = 'none';
       }

    });
    tf.init();
    </script>
{% endblock javascript %}

act/templates/meetings/organization_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block header %}
    <header class="bg-city">
      <div class="container-lg py-5">
          <div class="row">
              <div class="col text-white uppercase mr-5">
                <div class="row">
                    <div class="col my-auto pr-5">
                        <div><span class="fs45 fw700 lh-3">{{ object.name }} ({{ object.org_type }})</span></div>
                    </div>
                </div>
              </div>
              <div class="col-lg text-white my-auto">
                <div class="row mt-lg-0 mt-5">
                    <div class="col-auto evidenza"></div>
                    <div class="col fs18 my-auto">
                        <p class="fs18">
                        {% blocktrans with n_total=object.meetings.count %}
                            <span class="number">{{ n_total }}</span> meetings done
                        {% endblocktrans %}
                        {% if item.n_future_meetings > 0 %},
                            {% blocktrans with n_future=item.n_future_meetings %}
                                <span class="number">{{ n_future }}</span>
                                of which are programmed in the future
                            {% endblocktrans %}
                        {% endif %}
                        </p>
                        <div class="link-white mt-2"><a href="#meetings">{% trans "list of the meetings" %}</a></div>
                    </div>
                </div>
              </div>
          </div>
      </div>
    </header>
{% endblock %}

{% block content %}

    <main>

        <section id="dashboard" class="container-lg px-lg-4 mt-5">
            <div class="row mx-lg-n4">
                <div class="col-lg-6 mb-5">
                    {% include "meetings/includes/timeline_monthly_meetings.html" with items=timeline_monthly %}
                </div>
                <div class="col-lg-6 mb-5">
                    {% include "meetings/includes/issues_cloud.html" with items=issues_cloud %}
                </div>
            </div>

            <div class="row mx-lg-n4">
                <div class="col-lg mb-5 text-center">
                    <div class="row">
                        <div class="col title text-center">{% trans "Persons met" %}</div>
                    </div>
                    {% for item in object.representatives_met %}
                        <button type="button" class="btn btn-outline">
                            <a href="{% url 'meetings:representative_detail' item.pk %}">{{ item.name }}</a>
                        </button>
                    {% endfor %}
                </div>
            </div>

            <div class="row mx-lg-n4">
                <div class="col-lg mb-5">
                    <div class="row">
                        <br/>
                        <a id="meetings"></a>
                        <div class="col title text-center">{% trans "Meetings" %}</div>
                    </div>
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" href="#last-meetings" data-toggle="tab">{% trans "Last 5" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#next-meetings" data-toggle="tab">{% trans "Next 5" %}</a>
                        </li>
                        <div class="col text-right pt-1">
                            <a href='{% url 'meetings:meeting_list' %}#{"col_3"%3A{"flt"%3A"{{ object.name }}"}}'>{% trans "See all" %}</a>
                        </div>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="last-meetings">
                            {% include "meetings/includes/top_meetings_list.html" with items=object.last_n_meetings list_context="repr" all_url="" %}
                        </div>
                        <div class="tab-pane fade" id="next-meetings">
                            {% include "meetings/includes/top_meetings_list.html" with items=object.next_n_meetings list_context="repr" all_url="" %}
                        </div>

                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

act/templates/meetings/representative_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block header %}
  {% include "meetings/includes/page_list_header.html" with page_type="representatives_list" text=presentation_text.representatives_text %}
{% endblock header %}

{% block content %}

    <section id="items-container" class="container-lg px-lg-4">
        <div class="table-responsive-lg">
            <table id="items-data-table" class="table table-striped mt-4">
                <thead>
                    <tr>
                        <th scope="col">{% trans "Name" %}</th>
                        <th scope="col">{% trans "Post"%}</th>
                        <th scope="col">{% trans "Party"%}</th>
                        <th class="text-center" scope="col">{% trans "Active post"%}</th>
                        <th class="text-center" scope="col">{% trans "N. meetings"%}</th>
                        <th class="text-center" scope="col">{% trans "Last income"%}</th>
                        <th class="text-center" scope="col">{% trans "N. interests" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'meetings:representative_detail' item.pk %}">{{ item.given_name }} {{ item.family_name }}</a>
                            </td>
                            <td>
                                {{ item.post_type }}
                            </td>
                            <td>{{ item.party }}</td>
                            <td class="text-center">
                            {% if item.is_current %}
                                <div class="check"></div>
                            {% endif %}
                            </td>
                            <td class="number">
                                {{ item.n_meetings }}
                            </td>
                            <td class="number">
                                {{ item.last_income }}
                            </td>
                            <td class="number">
                                {{ item.n_interests }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}